services:
  artemis-broker:
    image: apache/activemq-artemis:2.40.0
    container_name: artemis-broker
    restart: unless-stopped
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - interop-network
    volumes:
      - artemis-data:/var/lib/artemis-instance
      - ./conf/artemis-users.properties:/var/lib/artemis-instance/etc/artemis-users.properties
      - ./conf/artemis-roles.properties:/var/lib/artemis-instance/etc/artemis-roles.properties
      - ./conf/broker.xml:/var/lib/artemis-instance/etc/broker.xml

networks:
  interop-network:
    name: interop-network
    driver: bridge

volumes:
  artemis-data:
    driver: local 